title: Project
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: main_text
        field:
          always_show_set_button: false
          buttons:
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - underline
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          display: 'Main text'
          type: bard
          icon: bard
          listable: hidden
      -
        handle: template
        field:
          hide_partials: true
          display: Template
          type: hidden
          listable: hidden
          default: project
      -
        handle: related_content
        field:
          mode: default
          collections:
            - pages
          display: 'Related content'
          type: entries
          icon: entries
          listable: hidden
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
